### ISSUE TITLE
Invalid_scope error

### ISSUE THREAD

**Issue by fellz** [acemtp/meteor-accounts-slack#1]
Hi
Getting this error 
  `OAuth error: invalid_scope: is an invalid scope`
in this http call: 

https://slack.com/oauth/authorize?client_id=5226385829.7225028496&response_type=code&redirect_uri=http://localhost:3000/_oauth/slack&state=eyJsb2dpblN0eWxlIjoicG9wdXAiLCJjcmVkZW50aWFsVG9rZW4iOiJEOWJGcWRlUkF4WmNzYm9QcCIsImlzQ29yZG92YSI6ZmFsc2V9

As stated in docs scope is optional, but maybe something changed. Seems like scope is required now..

**Comment by acemtp** [comment]
We had the same issue, I think Slack make the scope mandatory and didn't update the doc :(

I added requestPermissions options to be sure to always have a scope:

```
  Meteor.loginWithSlack({ requestPermissions: ['identify'] });
```

**Comment by fellz** [comment]
So where `scope` should be defined now ?

**Comment by acemtp** [comment]
just here:

```
Meteor.loginWithSlack({ requestPermissions: ['identify'] });
```

it'll put in the url scope=identify

**Comment by fellz** [comment]
Well i use {{> loginButtons }}. I guess it should be in click handler. May be add this stuff to the package to use with loginButtons template?

**Comment by acemtp** [comment]
done, just

```
meteor update acemtp:accounts-slack
```
