### ISSUE TITLE
Pass custom data when firing Meteor.loginWithSlack()

### ISSUE THREAD

**Issue by tomasz-nolberczak** [acemtp/meteor-accounts-slack#11]
Is it possible to pass some extra data as parameter during Meteor.loginWithSlack(), which could be accessible in Accounts.onCreateUser options? 

I mean something like:

```javascript

// client
const someData = "I want to get it from Accounts.onCreateUser";

Meteor.loginWithSlack({
    someData: someData
})

// server
Accounts.onCreateUser(function (options, user) {
    console.log(options.someData); // "I want to get it from Accounts.onCreateUser"
});
```

@acemtp Can we do this?

**Comment by tomasz-nolberczak** [comment]
@acemtp Can we do it in the future? Or the project is dead?

**Comment by acemtp** [comment]
The project is still working fine but I don't develop anything on it.
PR is welcome ;)

**Comment by tomasz-nolberczak** [comment]
It is no longer needed in my project. However, thank you!
